services:
  - type: web
    name: smart-parking-system
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RAZORPAY_KEY_ID
        sync: false  # This means you'll set it manually in the Render dashboard
      - key: RAZORPAY_KEY_SECRET
        sync: false  # This means you'll set it manually in the Render dashboard
    disk:
      name: data
      mountPath: /data
      sizeGB: 1